name: ci

on:
  push:
    branches:
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/evabot:latest
      -
        env:
          TOKEN: ${{ secrets.TOKEN }}
          HOST_DB: ${{ secrets.HOST_DB }}
          USER_DB: ${{ secrets.USER_DB }}
          PASSWD_DB: ${{ secrets.PASSWD_DB }}
          DB: ${{ secrets.DB }}
